// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://finsrwlvvxjsdfbryiei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpbnNyd2x2dnhqc2RmYnJ5aWVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NjQ4NDEsImV4cCI6MjA2MzU0MDg0MX0.UQnvM88zcOT97fV-Bhm4HbmHBw7s7mpanjt-8xDEpFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);